apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresscalls
  labels:
    app: stresscalls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stresscalls
  template:
    metadata:
      name: stresscalls
      labels:
        app: stresscalls
    spec:
      containers:
      - name: stresscalls
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- http://php-apache; done"
